name: CI

on: [ push, pull_request ]

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }} (${{ matrix.configuration }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain: [ windows-msvc ]

        configuration: [ Debug, Release ]
        
        include:
          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: SetUp MySQL
        uses: ankane/setup-mysql@v1
        with: 
          mysql-version: 8.0
          database: test_ormppdb

      - name: Verify MySQL
        run:  mysql -uroot -e'show databases;'

      - name: Configure cmake
        run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run:  cmake --build ${{github.workspace}}/build --config ${{ matrix.configuration }}

      - name: Test
        working-directory: ${{github.workspace}}/build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}
