name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  coverage_report:
  
    name: Generate coverage report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup MySQL
      uses: ankane/setup-mysql@v1
      with: 
        mysql-version: 8.0
        database: test_ormppdb

    - name: Verify MySQL
      run:  mysql -uroot -e'show databases;'

    - name: Configure cmake
      run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build with ${{ matrix.compiler }}
      run:  cmake --build ${{github.workspace}}/build --config Debug
      
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
