name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  coverage_report:
  
    name: Generate coverage report
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup MySQL
      uses: ankane/setup-mysql@v1
      with: 
        mysql-version: 8.0
        database: test_ormppdb

    - name: Verify MySQL
      run:  mysql -uroot -e'show databases;'

    - name: Configure cmake
      run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build with ${{ matrix.compiler }}
      run:  cmake --build ${{github.workspace}}/build --config Debug
    
    - name: Setup LCOV
      uses: hrishikesh-kadam/setup-lcov@v1
      
    - name: Report code coverage
      uses: zgosalvez/github-actions-report-lcov@v3
      with:
        coverage-files: coverage/lcov.*.info
        minimum-coverage: 90
        artifact-name: code-coverage-report
        github-token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{github.workspace}}/build/tests
        update-comment: true
