name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  coverage_report:
  
    name: Generate coverage report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup MySQL
      uses: ankane/setup-mysql@v1
      with: 
        mysql-version: 8.0
        database: test_ormppdb

    - name: Verify MySQL
      run:  mysql -uroot -e'show databases;'

    - name: Configure cmake
      run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build with ${{ matrix.compiler }}
      run:  cmake --build ${{github.workspace}}/build --config Debug

    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1.2

    - name: Install dependencies
      run: dart pub get

    - name: Generate Coverage
      working-directory: ${{github.workspace}}
      run: ./coverage.sh ${{github.workspace}}/build && ls -a ${{github.workspace}}/build && ls -a ${{github.workspace}}/build/coverage

    - name: Report Coverage
      uses: zgosalvez/github-actions-report-lcov@v1.3.2
      with:
        coverage-files: "${{github.workspace}}/build/coverage/*.info"
        github-token: ${{ secrets.GITHUB_TOKEN }}    
        artifact-name: common-coverage-report
        minimum-coverage: 0
