name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  coverage_report:
  
    name: Generate coverage report
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup MySQL
      uses: ankane/setup-mysql@v1
      with: 
        mysql-version: 8.0
        database: test_ormppdb

    - name: Verify MySQL
      run:  mysql -uroot -e'show databases;'

    - name: Configure cmake
      run:  cmake -B${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug

    - name: Build with ${{ matrix.compiler }}
      run:  cmake --build ${{github.workspace}}/build --config Debug
      
    - name: Generate a coverage value
      run: |
        COVERAGE="$( parse-coverage-report )"
        echo "##[set-output name=lines;]${COVERAGE}%"
        
    - name: Generate the badge SVG image
      uses: emibcn/badge-action@v1
      with:
          label: 'Test coverage'
          status: ${{ steps.coverage.outputs.lines }}
          color: 'blue,555,daf'
          path: badge.svg
