name: Upload CodeCov Report

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Prepare
        run: git init
        working-directory: ${{github.workspace}}
        
      - name: Run gcov2lcov-action with specific release
        uses: ./
        with:
          working-directory: ${{github.workspace}}
          version: v1.0.4
          
      - name: Diff
        run: diff -y coverage_expected.lcov coverage.lcov
        working-directory: ${{github.workspace}}
        
      - name: Run gcov2lcov-action with latest release
        uses: ./
        with:
          working-directory: ${{github.workspace}}
          
      - name: Diff
        run: diff -y coverage_expected.lcov coverage.lcov
        working-directory: ${{github.workspace}}
